package ventanas;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

public class Botones extends javax.swing.JFrame {

 
    public Botones() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(605, 440);
        setTitle("TIPOS DE APRENDIZAJE");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        this.repaint();
        cambiarIcono();
    }

    private void cambiarIcono() {
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/LOGO.png"));
        Image imagen = icono.getImage();

        this.setIconImage(imagen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_regresa = new javax.swing.JButton();
        jButton_quineztesico = new javax.swing.JButton();
        jButton_auditivo = new javax.swing.JButton();
        jButton_visual = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_regresa.setBackground(new java.awt.Color(214, 184, 232));
        jButton_regresa.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton_regresa.setText("Regresar");
        jButton_regresa.setBorder(null);
        jButton_regresa.setBorderPainted(false);
        jButton_regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_regresaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 180, 25));

        jButton_quineztesico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manos.png"))); // NOI18N
        jButton_quineztesico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quineztesicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_quineztesico, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 100, 80));

        jButton_auditivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auditivo.png"))); // NOI18N
        jButton_auditivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_auditivoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_auditivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 100, 80));

        jButton_visual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visual.png"))); // NOI18N
        jButton_visual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_visualActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_visual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, 80));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Quineztesico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("Auditivo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Visual");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paperMenu.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 628, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_regresaActionPerformed
        Menu n = new Menu();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_regresaActionPerformed

    private void jButton_visualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_visualActionPerformed
        Visual n = new Visual();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_visualActionPerformed

    private void jButton_auditivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_auditivoActionPerformed
        Auditivo n = new Auditivo();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_auditivoActionPerformed

    private void jButton_quineztesicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quineztesicoActionPerformed
        Kinestesico n = new Kinestesico();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_quineztesicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Botones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Botones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Botones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Botones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Botones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_auditivo;
    private javax.swing.JButton jButton_quineztesico;
    private javax.swing.JButton jButton_regresa;
    private javax.swing.JButton jButton_visual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
